# Generated by Django 2.2.2 on 2021-07-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
