# Generated by Django 2.2.2 on 2021-07-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMDB', '0002_auto_20210712_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('fav_genres', models.CharField(max_length=40)),
            ],
        ),
    ]
