# Generated by Django 2.2.2 on 2021-07-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMDB', '0003_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='fav_genres',
        ),
    ]
