# Generated by Django 2.2.2 on 2021-07-31 20:38

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('TMDB', '0005_auto_20210728_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='mgenres',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, null=True, size=3),
        ),
    ]
