# Generated by Django 2.2.2 on 2021-08-25 22:03

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('TMDB', '0006_auto_20210731_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AlterField(
            model_name='collection',
            name='mdescription',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='collection',
            name='mgenres',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=66, size=3),
        ),
        migrations.AlterField(
            model_name='collection',
            name='mtitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='muuid',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='movies',
            name='cuuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='TMDB.Collection'),
        ),
    ]
