# Generated by Django 2.2.2 on 2021-08-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMDB', '0007_auto_20210825_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='cuuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='TMDB.Collection', to_field='title'),
        ),
    ]
