# Generated by Django 2.2.2 on 2021-08-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMDB', '0008_auto_20210826_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cuuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='TMDB.Collection'),
        ),
    ]
