# Generated by Django 2.2.2 on 2021-08-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMDB', '0009_auto_20210826_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
