# Generated by Django 2.2.2 on 2021-08-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMDB', '0010_auto_20210826_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='cuuid',
            new_name='colluuid',
        ),
    ]
